### ISSUE TITLE
The `linkflags` option doesn't seem to work.

### ISSUE THREAD

**Issue by 0WAQ** [qqiangwu/cppship#86]

**Comment by qqiangwu** [comment]
Can you provide more information?

**Comment by 0WAQ** [comment]
> Can you provide more information?

For example:
```toml
[package]
name = "test"
version = "0.1.0"
std = 17

[profile]
cxxflags = ["-g"]
linkflags = ["-lpthread"]

[dependencies]
```
I've added the `linkflags` option, but it's still reported the `undefined reference to 'pthread_create'`. I'm not sure if I'm using it correctly(I use it the way the `cxxflags` option is used). And I just found out the `CMakeLists` or `Makefile` it generated doesn't have any link-related options;
